servers = [
    "0.pool.ntp.org",
    "1.pool.ntp.org",
    "2.pool.ntp.org",
    "3.pool.ntp.org",
    "time1.google.com",
    "time2.google.com",
    "time3.google.com",
    "time4.google.com",
    "time1.facebook.com",
    "time2.facebook.com",
    "time3.facebook.com",
    "time4.facebook.com",
    "time5.facebook.com",
    "time.apple.com",
    "time.cloudflare.com",
    "time.aws.com",
    "time.windows.com",
    "time.nist.gov",
    "ntp.ubuntu.com",
]
